#! /bin/sh
#bspc rule -r "*"


pgrep -x sxhkd > /dev/null || sxhkd &

#AUTOSTART#
~/.config/polybar/launch.sh
killall "nm-applet"
nm-applet &
killall picom
picom -b -c -C  &
feh --bg-fill --no-fehbg ~/Pictures/minimalistdark.jpg &
xinput --set-prop 12 'Coordinate Transformation Matrix' 1, 0, 0, 0, 1, 0, 0, 0, 1.75 &
#xrdb ~/.Xresources &
#wal -R & 

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         20
bspc config window_gap           20

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
#bspc config focused_border_color  \#632d65
#bspc config normal_border_color \#111824
bspc config border_width	2
bspc config border_padding      10

bspc rule -a firefox desktop='^2' follow=on
bspc rule -a Emacs desktop='^1' state=tiled
#bspc rule -a Gimp desktop=8 state=floating follow=on
#bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bash /home/varad/.config/bspwm/bspwm_colors.sh &
